### ISSUE TITLE
豆瓣API是改了吗？看到运行出来没有数据，不过你的代码里面确实是有请求数据的

### ISSUE THREAD

**Issue by JserJser** [lypeng29/react-native-book#1]
![image](https://user-images.githubusercontent.com/30041386/58307029-0477c980-7e30-11e9-96a3-53a053224a92.png)

**Comment by lypeng29** [comment]
我这也请求不到了，应该是接口调整了

**Comment by lypeng29** [comment]
@JserJser 看我另一个案例，RN_news
